### ISSUE TITLE
Consistent Profiling

### ISSUE THREAD

**Issue by mattxwang** [just-the-docs/just-the-docs-tests#2]
@pdmosses a quick question: would you prefer for me to start contributing to profiling efforts (since I recognize that you often have to do a *ton* of work after each release!), or is it better for all the profiling to happen on your laptop (to keep the results consistent)? Happy to help out however I can!

**Comment by pdmosses** [comment]
@mattxwang thanks for asking, but in fact updating the profiling page to a new release or PR is very little work.

For example, here's a log of all I needed to do to add profiles for v0.8.1:

### Create the new profile data

1. In the [`makefile`](https://github.com/just-the-docs/just-the-docs-tests/blob/main/makefile)  replace `v0.8.0` by `v0.8.1`
2. In a local clone of the `just-the-docs-tests` repo execute `make dirs; make profiles`

```
just-the-docs-tests: make dirs; make profiles
Creating any missing directories
Creating any missing directories
collections/_tests/profiles/endoflife.date/3.9.3/just-the-docs/v0.8.1
collections/_tests/profiles/endoflife.date/4.3.2/just-the-docs/v0.8.1
collections/_tests/profiles/jekyll-doc-tsl2/3.9.3/just-the-docs/v0.8.1
collections/_tests/profiles/jekyll-doc-tsl2/4.3.2/just-the-docs/v0.8.1
collections/_tests/profiles/just-the-docs-tests/3.9.3/just-the-docs/v0.8.1
collections/_tests/profiles/just-the-docs-tests/4.3.2/just-the-docs/v0.8.1
collections/_tests/profiles/machinetranslate.org/3.9.3/just-the-docs/v0.8.1
[...]
collections/_tests/profiles/machinetranslate.org/4.3.2/just-the-docs/v0.8.1
[...]
just-the-docs-tests: 
```

On the laptop I'm using, the `make` command takes less than 3 minutes, with no interaction.

Optionally, execute `make` or `make help` for further info.

### Update the source files

1. In [`_includes/profiles/jekyll.md`](https://github.com/just-the-docs/just-the-docs-tests/blob/main/_includes/profiles/jekyll.md?plain=1)  replace `v0.8.0` by `v0.8.1`
2. In [`_includes/profiles/site.md`](https://github.com/just-the-docs/just-the-docs-tests/blob/main/_includes/profiles/site.md?plain=1)  replace `v0.8.0` by `v0.8.1`, and replace `time_0_8_0` by `time_0_8_1`
3. In [`collections/_tests/profiles/index.md`](https://github.com/just-the-docs/just-the-docs-tests/blob/main/collections/_tests/profiles/index.md?plain=1)  replace `v0.8.0` by `v0.8.1`

### Update the website

1. Run `bundle exec jekyll serve`
2. Browse [`tests/profiles/index/`](http://localhost:4000/just-the-docs-tests/tests/profiles/index/)
3. Commit the changes to the repo
4. The updated profiles appear on the tests site at [`tests/profiles/index/`](https://just-the-docs.github.io/just-the-docs-tests/tests/profiles/index/)

🎉

**Comment by mattxwang** [comment]
Sounds great - will close this issue for now to avoid filling it up. Your comment will be super helpful if I ever need to give it a spin in the future. Thank you!
